name = "EnergyInfrastructureOptimization"
uuid = "3f088926-ec43-4649-904e-a6756e7e885d"
authors = ["Tom Van Acker"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
